# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Basic code quality rules
    avoid_print: true # Avoid using print statements for logging
    prefer_const_constructors: true # Prefer const constructors where possible
    prefer_final_locals: true # Prefer declaring local variables as final if they are not reassigned

    # Code style rules
    prefer_single_quotes: true # Prefer single quotes for string literals
    always_use_package_imports: true # Prefer package imports (package:my_package/my_file.dart)

    # Code organization rules
    sort_pub_dependencies: true # Ensure pub dependencies are sorted alphabetically
    file_names: true # Ensure file names are lowercase_with_underscores

    # Flutter specific rules
    avoid_unnecessary_containers: true # Avoid unnecessary container widgets
    prefer_const_constructors_in_immutables: true # Prefer const constructors in @immutable classes
    sized_box_for_whitespace: true # Use SizedBox for whitespace in a layout

    # Error handling and null safety
    avoid_returning_null_for_void: true # Avoid returning null from void methods
    null_closures: true # Avoid null in closure bodies

    # Performance optimizations
    avoid_redundant_argument_values: true # Avoid specifying argument values that match their defaults
    curly_braces_in_flow_control_structures: true # Always put curly braces around blocks in control flow structures
    require_trailing_commas: false # Require trailing commas in argument lists and literals

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
